name: Run Slow Unit Tests

on: [push, pull_request]

jobs:
  rest_client:
    name: REST Client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/_restclient[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/_restclient/
  nwis_client:
    name: NWIS Client
    needs: rest_client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/_restclient[develop]
        python3 -m pip install ./python/nwis_client[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/nwis_client/
  caches:
    name: Caches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/caches[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/caches/
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/metrics[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/metrics/
  nwm_client:
    name: NWM Client
    needs: caches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/nwm_client[gcp,develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/nwm_client/
  nwm_client_new:
    name: NWM Client New
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/nwm_client_new[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/nwm_client_new/
  events:
    name: Events
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/events[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/events/
  svi_client:
    name: SVI Client
    needs: rest_client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/svi_client[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run all unittests 
      run: |
        python3 -m pytest -s python/svi_client/
